{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "489e18c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import numpy as np\n",
    "import cv2\n",
    "import natsort\n",
    "import xlwt\n",
    "import datetime\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "dd4c5a07",
   "metadata": {},
   "outputs": [],
   "source": [
    "# color equalisation\n",
    "\n",
    "def cal_equalisation(img,ratio):\n",
    "    Array = img * ratio\n",
    "    Array = np.clip(Array, 0, 255)\n",
    "    return Array\n",
    "\n",
    "def RGB_equalisation(img):\n",
    "    img = np.float32(img)\n",
    "    avg_RGB = []\n",
    "    for i in range(3):\n",
    "        avg = np.mean(img[:,:,i])\n",
    "        avg_RGB.append(avg)\n",
    "    # print('avg_RGB',avg_RGB)\n",
    "    a_r = avg_RGB[0]/avg_RGB[2]\n",
    "    a_g =  avg_RGB[0]/avg_RGB[1]\n",
    "    ratio = [0,a_g,a_r]\n",
    "    for i in range(1,3):\n",
    "        img[:,:,i] = cal_equalisation(img[:,:,i],ratio[i])\n",
    "    return img\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e4afc00f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# global histogram streching\n",
    "\n",
    "def histogram_r(r_array,height, width):\n",
    "    length = height * width\n",
    "    R_rray = []\n",
    "    for i in range(height):\n",
    "        for j in range(width):\n",
    "            R_rray.append(r_array[i][j])\n",
    "    R_rray.sort()\n",
    "    I_min = int(R_rray[int(length / 500)])\n",
    "    I_max = int(R_rray[-int(length / 500)])\n",
    "    array_Global_histogram_stretching = np.zeros((height, width))\n",
    "    for i in range(0, height):\n",
    "        for j in range(0, width):\n",
    "            if r_array[i][j] < I_min:\n",
    "                # p_out = r_array[i][j]\n",
    "                array_Global_histogram_stretching[i][j] = I_min\n",
    "            elif (r_array[i][j] > I_max):\n",
    "                p_out = r_array[i][j]\n",
    "                array_Global_histogram_stretching[i][j] = 255\n",
    "            else:\n",
    "                p_out = int((r_array[i][j] - I_min) * ((255 - I_min) / (I_max - I_min)))+ I_min\n",
    "                array_Global_histogram_stretching[i][j] = p_out\n",
    "    return (array_Global_histogram_stretching)\n",
    "\n",
    "def histogram_g(r_array,height, width):\n",
    "    length = height * width\n",
    "    R_rray = []\n",
    "    for i in range(height):\n",
    "        for j in range(width):\n",
    "            R_rray.append(r_array[i][j])\n",
    "    R_rray.sort()\n",
    "    I_min = int(R_rray[int(length / 500)])\n",
    "    I_max = int(R_rray[-int(length / 500)])\n",
    "    array_Global_histogram_stretching = np.zeros((height, width))\n",
    "    for i in range(0, height):\n",
    "        for j in range(0, width):\n",
    "            if r_array[i][j] < I_min:\n",
    "                p_out = r_array[i][j]\n",
    "                array_Global_histogram_stretching[i][j] = 0\n",
    "            elif (r_array[i][j] > I_max):\n",
    "                p_out = r_array[i][j]\n",
    "                array_Global_histogram_stretching[i][j] = 255\n",
    "            else:\n",
    "                p_out = int((r_array[i][j] - I_min) * ((255) / (I_max - I_min)) )\n",
    "                array_Global_histogram_stretching[i][j] = p_out\n",
    "    return (array_Global_histogram_stretching)\n",
    "\n",
    "def histogram_b(r_array,height, width):\n",
    "    length = height * width\n",
    "    R_rray = []\n",
    "    for i in range(height):\n",
    "        for j in range(width):\n",
    "            R_rray.append(r_array[i][j])\n",
    "    R_rray.sort()\n",
    "    I_min = int(R_rray[int(length / 500)])\n",
    "    I_max = int(R_rray[-int(length / 500)])\n",
    "    array_Global_histogram_stretching = np.zeros((height, width))\n",
    "    for i in range(0, height):\n",
    "        for j in range(0, width):\n",
    "            if r_array[i][j] < I_min:\n",
    "                # p_out = r_array[i][j]\n",
    "                array_Global_histogram_stretching[i][j] = 0\n",
    "            elif (r_array[i][j] > I_max):\n",
    "                # p_out = r_array[i][j]\n",
    "                array_Global_histogram_stretching[i][j] = I_max\n",
    "            else:\n",
    "                p_out = int((r_array[i][j] - I_min) * ((I_max) / (I_max - I_min)))\n",
    "                array_Global_histogram_stretching[i][j] = p_out\n",
    "    return (array_Global_histogram_stretching)\n",
    "\n",
    "def stretching(img):\n",
    "    height = len(img)\n",
    "    width = len(img[0])\n",
    "    img[:, :, 2] = histogram_r(img[:, :, 2], height, width)\n",
    "    img[:, :, 1] = histogram_g(img[:, :, 1], height, width)\n",
    "    img[:, :, 0] = histogram_b(img[:, :, 0], height, width)\n",
    "    return img\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "5ac9f3af",
   "metadata": {},
   "outputs": [],
   "source": [
    "# global streching\n",
    "\n",
    "def global_stretching(img_L,height, width):\n",
    "    I_min = np.min(img_L)\n",
    "    I_max = np.max(img_L)\n",
    "    I_mean = np.mean(img_L)\n",
    "\n",
    "\n",
    "    # print('I_min',I_min)\n",
    "    # print('I_max',I_max)\n",
    "    # print('I_max',I_mean)\n",
    "\n",
    "    array_Global_histogram_stretching_L = np.zeros((height, width))\n",
    "    for i in range(0, height):\n",
    "        for j in range(0, width):\n",
    "            p_out = (img_L[i][j] - I_min) * ((1) / (I_max - I_min))\n",
    "            array_Global_histogram_stretching_L[i][j] = p_out\n",
    "\n",
    "    return array_Global_histogram_stretching_L\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "70777281",
   "metadata": {},
   "outputs": [],
   "source": [
    "# HSV Streching\n",
    "\n",
    "def  HSVStretching(sceneRadiance):\n",
    "    sceneRadiance = np.uint8(sceneRadiance)\n",
    "    height = len(sceneRadiance)\n",
    "    width = len(sceneRadiance[0])\n",
    "    img_hsv = cv2.cvtColor(sceneRadiance, cv2.COLOR_BGR2HSV)\n",
    "\n",
    "    h, s, v = cv2.split(img_hsv)\n",
    "    img_s_stretching = global_stretching(s, height, width)\n",
    "    img_v_stretching = global_stretching(v, height, width)\n",
    "\n",
    "    labArray = np.zeros((height, width, 3), 'float64')\n",
    "    labArray[:, :, 0] = h\n",
    "    labArray[:, :, 1] = img_s_stretching\n",
    "    labArray[:, :, 2] = img_v_stretching\n",
    "    image_hsv_correct_depth = labArray.astype('float32')\n",
    "    img_rgb = cv2.cvtColor(image_hsv_correct_depth, cv2.COLOR_HSV2BGR) * 255\n",
    "\n",
    "    # img_rgb = np.clip(img_rgb, 0, 255)\n",
    "\n",
    "    return img_rgb\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "66a2bc04",
   "metadata": {},
   "outputs": [],
   "source": [
    "# scene radiance\n",
    "\n",
    "def sceneRadianceRGB(sceneRadiance):\n",
    "\n",
    "    sceneRadiance = np.clip(sceneRadiance, 0, 255)\n",
    "    sceneRadiance = np.uint8(sceneRadiance)\n",
    "\n",
    "    return sceneRadiance\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "7c1d5d9a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "********    file   ******** 2.png\n",
      "********    file   ******** 5.png\n",
      "********    file   ******** 34.png\n",
      "********    file   ******** 52.png\n",
      "********    file   ******** 102.png\n",
      "********    file   ******** 358_img_.png\n",
      "********    file   ******** 432.png\n",
      "********    file   ******** 579.png\n",
      "********    file   ******** 605.png\n",
      "********    file   ******** 616.png\n",
      "********    file   ******** 627.png\n",
      "********    file   ******** 643_img_.png\n",
      "********    file   ******** 770.png\n",
      "********    file   ******** 866.png\n",
      "********    file   ******** 880.png\n",
      "********    file   ******** 2575.png\n",
      "********    file   ******** 2583.png\n",
      "********    file   ******** 2856.png\n",
      "********    file   ******** 3027.png\n",
      "********    file   ******** 3051.png\n",
      "********    file   ******** 3087.png\n",
      "********    file   ******** 3175.png\n",
      "********    file   ******** 3201.png\n",
      "********    file   ******** 3279.png\n",
      "********    file   ******** 3494.png\n",
      "********    file   ******** 3519.png\n",
      "********    file   ******** 6333.png\n",
      "********    file   ******** 6340.png\n",
      "********    file   ******** 6527.png\n",
      "********    file   ******** 7277.png\n",
      "********    file   ******** 7291.png\n",
      "********    file   ******** 9553.png\n",
      "********    file   ******** 9602.png\n",
      "********    file   ******** 9607.png\n",
      "********    file   ******** 9618.png\n",
      "********    file   ******** 10091.png\n",
      "********    file   ******** 10103.png\n",
      "********    file   ******** 10167.png\n",
      "********    file   ******** 10226.png\n",
      "********    file   ******** 10475.png\n",
      "********    file   ******** 10488.png\n",
      "********    file   ******** 12191.png\n",
      "********    file   ******** 12203.png\n",
      "********    file   ******** 12228.png\n",
      "********    file   ******** 12565.png\n",
      "********    file   ******** 12577.png\n",
      "********    file   ******** 12625.png\n",
      "********    file   ******** 12709.png\n",
      "********    file   ******** 12753.png\n",
      "********    file   ******** 12960.png\n",
      "********    file   ******** 12972.png\n",
      "********    file   ******** 13252.png\n",
      "********    file   ******** 13259.png\n",
      "********    file   ******** 15735.png\n",
      "********    file   ******** 15738.png\n",
      "********    file   ******** 15740.png\n",
      "********    file   ******** 15774.png\n",
      "********    file   ******** 15775.png\n",
      "********    file   ******** 100001.png\n"
     ]
    },
    {
     "ename": "NameError",
     "evalue": "name 'starttime' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn [7], line 29\u001b[0m\n\u001b[0;32m     26\u001b[0m         cv2\u001b[38;5;241m.\u001b[39mimwrite(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mOutputImages/\u001b[39m\u001b[38;5;124m'\u001b[39m \u001b[38;5;241m+\u001b[39m prefix \u001b[38;5;241m+\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124m_UCM.jpg\u001b[39m\u001b[38;5;124m'\u001b[39m, sceneRadiance)\n\u001b[0;32m     28\u001b[0m endtime \u001b[38;5;241m=\u001b[39m datetime\u001b[38;5;241m.\u001b[39mdatetime\u001b[38;5;241m.\u001b[39mnow()\n\u001b[1;32m---> 29\u001b[0m time \u001b[38;5;241m=\u001b[39m endtime\u001b[38;5;241m-\u001b[39m\u001b[43mstarttime\u001b[49m\n\u001b[0;32m     30\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtime\u001b[39m\u001b[38;5;124m'\u001b[39m,time)\n",
      "\u001b[1;31mNameError\u001b[0m: name 'starttime' is not defined"
     ]
    }
   ],
   "source": [
    "\n",
    "np.seterr(over='ignore')\n",
    "if __name__ == '__main__':\n",
    "    pass\n",
    "\n",
    "# folder = \"C:/Users/Administrator/Desktop/UnderwaterImageEnhancement/NonPhysical/UCM\"\n",
    "folder = r\"C:\\Users\\Saptarshi\\Project\\Enhance\"\n",
    "\n",
    "path = folder + \"/InputImages\"\n",
    "files = os.listdir(path)\n",
    "files =  natsort.natsorted(files)\n",
    "\n",
    "for i in range(len(files)):\n",
    "    file = files[i]\n",
    "    filepath = path + \"/\" + file\n",
    "    prefix = file.split('.')[0]\n",
    "    if os.path.isfile(filepath):\n",
    "        print('********    file   ********',file)\n",
    "        # img = cv2.imread('InputImages/' + file)\n",
    "        img = cv2.imread(folder + '/InputImages/' + file)\n",
    "        # print('Number',Number)\n",
    "        sceneRadiance = RGB_equalisation(img)\n",
    "        sceneRadiance = stretching(sceneRadiance)\n",
    "        # cv2.imwrite(folder + '/OutputImages/' + Number + 'Stretched.jpg', sceneRadiance)\n",
    "        sceneRadiance = HSVStretching(sceneRadiance)\n",
    "        sceneRadiance = sceneRadianceRGB(sceneRadiance)\n",
    "        cv2.imwrite('OutputImages/' + prefix + '_UCM.jpg', sceneRadiance)\n",
    "\n",
    "endtime = datetime.datetime.now()\n",
    "time = endtime-starttime\n",
    "print('time',time)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fdf6a169",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
